"""
On my/our honor, Shasa Lloyd Kolar and Ethan Gomez, this 
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: SLK2633
UT EID 2: EGB664
"""


class Node:
    """
    A modified version of the Node class for linked lists (using proper class
    coding practices). Instead of a data instance variable, this node class has both
    a coefficient and an exponent instance variable, which is used to represent each
    term in a polynomial.
    """

    def __init__(self, coeff, exp, link=None):
        """
        Node Constructor for polynomial linked lists.

        Args:
        - coeff: The coefficient of the term.
        - exp: The exponent of the term.
        - link: The next node in the linked list.
        """
        self.coeff = coeff
        self.exp = exp
        self.next = link

    @property
    def coeff(self):
        """
        Getter method for the coefficient attribute.
        """
        return self.__coeff

    @coeff.setter
    def coeff(self, value):
        """
        Setter method for the coefficient attribute.
        """
        if value is None or isinstance(value, int):
            self.__coeff = value
        else:
            raise ValueError("Coefficient must be an integer or None.")

    @property
    def exp(self):
        """
        Getter method for the exponent attribute.
        """
        return self.__exp

    @exp.setter
    def exp(self, value):
        """
        Setter method for the exponent attribute.
        """
        if value is None or isinstance(value, int):
            self.__exp = value
        else:
            raise ValueError("Exponent must be an integer or None.")

    @property
    def next(self):
        """
        Getter method for the next attribute.
        """
        return self.__next

    @next.setter
    def next(self, value):
        """
        Setter method for the next attribute.
        """
        if value is None or isinstance(value, Node):
            self.__next = value
        else:
            raise ValueError("Next must be a Node instance or None.")

    def __str__(self):
        """
        String representation of each term in a polynomial linked list.
        """
        return f"({self.coeff}, {self.exp})"


class LinkedList:
    def __init__(self):
        # You are also welcome to use a sentinel/dummy node!
        # It is definitely recommended, which will we learn more
        # about in class on Monday 10/21. If you choose to use
        # a dummy node, you can comment out the self.head = None
        # and comment in the below line. We use None to make sure
        # if there is an error where you accidentally include the
        # dummy node in your calculation, it will throw an error.
        # self.dummy = Node(None, None)
        self.head = None

    # Insert the term with the coefficient coeff and exponent exp into the polynomial.
    # If a term with that exponent already exists, add the coefficients together.
    # You must keep the terms in descending order by exponent.
    def insert_term(self, coeff, exp):
        term = Node(coeff, exp, None)

        if term.coeff == 0:
            return

        # Empty List
        if self.head is None:
            self.head = term

        # List w one term
        if self.head.next == None:
            if term.exp < self.head.exp:
                #TODO order of exponents 
                self.head.next = term

            if term.exp > self.head.exp:
                term.next = self.head
                self.head = term

            if term.exp == self.head.exp:
                totalVal = term.coeff + self.head.coeff
                self.head.coeff = totalVal
                if totalVal == 0:
                    self.head = None

        # List w > 2 nodes
        itr = self.head
        while itr and itr.next:

            if term.exp == itr.next.exp:
                totalVal = term.coeff + itr.next.coeff
                if totalVal == 0:
                    itr.next = itr.next.next
                itr.coeff = totalVal
                break

            if term.exp > itr.next.exp:
                # TODO make it stay front :)
                term.next = itr.next
                itr.next = term
                break

            itr = itr.next

        term.next = itr.next
        itr.next = term

    # Add a polynomial p to the polynomial and return the resulting polynomial as a new linked list.
    def add(self, p, q):
        # same thing as 3rd and 4th loops in mult

    # Multiply a polynomial p with the polynomial and return the product as a new linked list.
    def mult(self, p, q):
        # have two for loops, an inner and out loop, inner loop is the length of the first polynomials singly linked list
        # outer loop is the length of the second polynomials singly linked list
        # first number, the coefficient is multiplied, the second number the exponent is added
        # the resulting term is inserted into the new linked list
        # finally a third and fourth loop (probably best to have them be while loops,
        # since we will delete elements of the linked lists) go through the new linked list
        # and check for terms with the same exponent, the coefficients will be added together and replace the initial term


    # Return a string representation of the polynomial.
    def __str__(self):
        polynomial_str = ""
        inbetween = " + "
        current = self.head
        while current is not None:
            if len(polynomial_str) == 0:
                polynomial_str = polynomial_str + str(current)
            else:
                polynomial_str = polynomial_str + inbetween
                polynomial_str = polynomial_str + str(current)
            current = current.next
        return polynomial_str


def main():
    # read data from stdin using input() and create polynomial p

    # read data from stdin using input() and create polynomial q

    # get sum of p and q as a new linked list and print sum

    # get product of p and q as a new linked list and print product
    polynomial1 = LinkedList()
    polynomial_term_length = input()
    for i in range(polynomial_term_length):
        polynomial1.insert_term(input())

    input()

    polynomial2 = LinkedList()
    polynomial_term_length = input()
    for i in range(polynomial_term_length):
        polynomial2.insert_term(input())
    
    added_polynomial = LinkedList()
    added_polynomial.add(polynomial1, polynomial2)
    print(added_polynomial)

    multiplied_polynomial = LinkedList()
    multiplied_polynomial.mult(polynomial1, polynomial2)
    print(multiplied_polynomial)



if __name__ == "__main__":
    main()
