"""
On my honor, Shasa Lloyd Kolar, this 
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: SLK2633
"""



def group_sum(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    # solution: get out notebook and draw out how the sum would work, should be simple
    if (len(nums) == 0 and target == 0) or (len(nums) == 1 and nums[0] == target) or start > len(nums)-1:
        return True
    elif len(nums) == 0 or len(nums) == 1:
        return False
    i = 0 # for iterating through the list
    init_list_item = 0 # outer "for loop" iterable
    current_sum = 0
    return solve_group_sum(nums, i, init_list_item, target, current_sum)


def solve_group_sum(nums, i, init_list_item, target, current_sum):
    if i == init_list_item:
        if i == len(nums) - 1:
            return False
        elif init_list_item == 0:
            if nums[0] == target:
                return True
            else:
                return solve_group_sum(nums, i + 1, init_list_item, target, nums[0]) or solve_group_sum(nums, i + 1, init_list_item, target, 0)
        elif i < len(nums) - 1:
            return solve_group_sum(nums, i + 1, init_list_item, target, current_sum) or solve_group_sum(nums, i + 1, init_list_item, target, current_sum - nums[i-1])
    elif i == len(nums) - 1:
        return solve_group_sum(nums, 0, init_list_item + 1, target, nums[init_list_item + 1]) or solve_group_sum(nums, 0, init_list_item + 1, target, 0)
    elif current_sum + nums[i] == target:
        return True
    else:
        return solve_group_sum(nums, i + 1, init_list_item, target, current_sum + nums[i]) or solve_group_sum(nums, i + 1, init_list_item, target, current_sum) or solve_group_sum(nums, i + 1, init_list_item, target, current_sum - nums[i-1])


# TODO: Modify this function. You may delete this comment when you are done.
def group_sum_6(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target. Additionally, if there is are 6's present in the array, they must all
    be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    return True


# TODO: Modify this function. You may delete this comment when you are done.
def group_no_adj(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a value is chosen, the value immediately after
    (the value adjacent) cannot be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    # solution: when iterating, iterable increases by 2 whenever a value is selected to be included
    # otherwise if the value was not selected iterable increases by 1, otherwise identical to original sum
    return True


# TODO: Modify this function. You may delete this comment when you are done.
def group_sum_5(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a multiple of 5 is in the array, it must be included
    If the value immediately following a multiple of 5 if 1, it must not be chosen

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    return True


# TODO: Modify this function. You may delete this comment when you are done.
def group_sum_clump(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if there is a group of identical numbers in succession,
    they must all be chosen, or none of them must be chosen.
    EX: [1, 2, 2, 2, 5, 2], all three of the middle 2's must be chosen, or none of them must be
    chosen to be included in the sum. One loop is allowed to check for identical numbers.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    return True


# TODO: Modify this function
def split_array(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    return True


# TODO: Modify this function. You may delete this comment when you are done.
def split_odd_10(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of one group must be odd, while the other group must be a multiple of 10
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    return True



# TODO: Modify this function. You may delete this comment when you are done.
def split_53(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Additionally, all multiples of 5 must be in one group, and all multiples of 3 (and not 5)
    must be in the other group
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    return True
